import { formDetails } from "./formDetails";
const {
  formField: {
    firstName,
    lastName,
    gender,
    dateOfBirth,
    address1,
    address2,
    city,
    state,
    zipCode,
    country,
    mobileNo,
    emailAdd,
    higherEducation,
    graduation,
    postGraduation,
    higherEducationMarksInPerc,
    graduationMarksInPerc,
    postGraduationMarksInPerc,
    schoolOfHigherEducation,
    collegeGraduation,
    collegePostGraduation,
    totalWorkExpInMonths,
    jobTitle,
    employer,
    startDate,
    currentlyWorking,
    achievements,
  },
} = formDetails;

const formKeys = {
  [firstName.name]: "",
  [lastName.name]: "",
  [gender.name]: "",
  [dateOfBirth.name]: "",
  [address1.name]: "",
  [address2.name]: "",
  [city.name]: "",
  [state.name]: "",
  [zipCode.name]: "",
  [country.name]: "",
  [mobileNo.name]: "",
  [emailAdd.name]: "",
  [higherEducation.name]: "",
  [graduation.name]: "",
  [postGraduation.name]: "",
  [higherEducationMarksInPerc.name]: "",
  [graduationMarksInPerc.name]: "",
  [postGraduationMarksInPerc.name]: "",
  [schoolOfHigherEducation.name]: "",
  [collegeGraduation.name]: "",
  [collegePostGraduation.name]: "",
  [totalWorkExpInMonths.name]: "",
  [jobTitle.name]: "",
  [employer.name]: "",
  [startDate.name]: "",
  [currentlyWorking.name]: "",
  [achievements.name]: "",
};

export default formKeys;
